apiVersion: apps/v1
network:
  forwarded_ports:
    - 8080/tcp
kind: Deployment
entrypoint: gunicorn -b :$PORT -b :8080 main:app
ports:
    - name: http1
      containerPort: 8080
metadata:
  name: mymlapp
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
